### ISSUE TITLE
关于其他型号

### ISSUE THREAD

**Issue by Avantyjw** [ALbur/HanFI#3]
想问问大佬 我想编译ufi003的 我需要在您的源码更改哪些

**Comment by ALbur** [comment]
如果用卡的话 应该换modem就行 其余的也许通用，我有001c和003的设备当时测试过

**Comment by Avantyjw** [comment]
去哪替换啊

**Comment by Avantyjw** [comment]
我把之前能用的debian的modem移过来能用吗

**Comment by ALbur** [comment]
将原来安卓的modem分区备份出来解包后放入/usr/lib/firmware

**Comment by ALbur** [comment]
1

**Comment by Avantyjw** [comment]
是刷完op之后替换的意思吧 我用miko备份的整包

**Comment by ALbur** [comment]
是的
